### PR TITLE
Canvas 2022

### PR DESCRIPTION
**Pull request by nikimacm**
# Zero To Mastery - Canvas 2022 🎉🎉

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## PR contains:
An animation using <canvas> element and Javascript.  I created a wheel by making 20 sections to make a circle with black and white panels. When page is loaded wheel looks like a fan. When pedal button is clicked on the wheel opens up and rotates around the center of the circle.

## Breaking changes
 'None'

## Screenshots
icon

### CODE REVIEW

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
Remove changes to `package-lock.json, package.json` and `.gitpod.yml`.

**Comment by nikimacm** [comment]
Hi. Regarding the message from Sofia Brant, do I need to implement these
changes?
Thank you!

**Comment by nikimacm** [comment]
Thank you very much.

**Comment by auxfuse** [comment]
@nikimacm Thanks for making the other changes, but the `package-lock,json` file still needs to be reverted. We won't be able to merge this until that is done. 😄 🤜

**Review by auxfuse — CHANGES_REQUESTED** [review]
`package-lock.json` file still needs reverting before approving and merging.

**Comment by nikimacm** [comment]
Thank you. I have reverted it.

**Review by auxfuse — APPROVED** [review]
Thanks for the changes @nikimacm 🤜 Approved! 👏

**Comment by nikimacm** [comment]
Thank you!!

**Pull request merged**
