### PR TITLE
Two Squares — Hacktoberfest

### PR DESCRIPTION
**Pull request by omicreativedev**
# Zero To Mastery - Canvas 2022 🎉🎉

## PR contains:
I made a square in a square. I'm still learning. I paid for the Udemy course to learn better.

## Breaking changes
None

## Screenshots
squares

### CODE REVIEW

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
Please rename the png file to `src/art/omicreativedev/icon.png` (basically rename from `squares.png` to `icon.png`, so that your screenshot shows up).

**Comment by omicreativedev** [comment]
Thank you for the change request. I'll get to it right after class. Still learning! Appreciate the feedback!

**Comment by auxfuse** [comment]
@omicreativedev let us know when you have made the requested changes and we can re-review 🤜 When you have the change made, don't forget to add it / commit / and push back to the branch associated with this PR to update.

**Review by bk987 — CHANGES_REQUESTED** [review]
`meta.json` file is missing, you should add that as well as per the instructions in the README.

**Comment by auxfuse** [comment]
> `meta.json` file is missing, you should add that as well as per the instructions in the README.

Yep, hence the re-review 😉

**Comment by MattCSmith** [comment]
Closing this PR due to an unresolved change request. Feel free to resolve and reopen

**Pull request closed without merging**
